//
//  Untitled.swift
//  Danjaumkey
//
//  Created by 지대선 on 8/16/25.
//  Copyright © 2025 Nextplan. All rights reserved.
//

[[headers]]
  for = "/apple-app-site-association"
  [headers.values]
    Content-Type = "application/json"
