
[build]
  publish = "public"

[[headers]]
  for = "/apple-app-site-association"
  [headers]
    "Content-Type" = "application/json"

[[headers]]
  for = "/.well-known/apple-app-site-association"
  [headers]
    "Content-Type" = "application/json"

